[project]
name = "word-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.8",
    "augraphy>=8.2.6",
    "dotenv>=0.9.9",
    "huggingface>=0.0.1",
    "huggingface-hub>=1.4.1",
    "opencv-python-headless>=4.13.0.92",
]

[project.scripts]
main = "word_detection.main:main"

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"
