[project]
name = "word-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "augraphy>=8.2.6",
    "opencv-python-headless>=4.13.0.92",
]

[project.scripts]
word-detection = "word_detection:main"

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"
